### ISSUE TITLE
External Reconciliation Services and how to move text subjects into LoD

### ISSUE THREAD

**Issue by DiegoPino** [esmero/ami#1]
# What is this?

An open discussion with @alliomeria on how to build a good LoD reconciliation UI/UX interface when you are migrating data or when you are doing Mass/Batch replaces.

This is a stub yet because the proper best UI/UX will come from @alliomeria's use case/needs and i will then work around that.

Thanks for watching

**Comment by dmer** [comment]
Very interested in seeing how this develops! I'd be happy to see user stories in development, and will attempt to write up a few that I have already in the back of my mind. Question - is this a component of a UI/UX tool for metadata cleanup? I'm hoping for a UI-based tool that allows repo admins to "collapse" differently spelled subjects or names or etc... across their collections. It would make sense to combine that with linking the term or entity to an LoD authority.

**Comment by DiegoPino** [comment]
Resolved
