### ISSUE TITLE
Only require >=2 Columns when doing Updates. Require 3+ when ingesting?

### ISSUE THREAD

**Issue by DiegoPino** [esmero/ami#102]
# What?

An Update operation really requires only a `node_uuid` and something to update. So 2 columns in a CSV

Reported by @karomabiles!

**Comment by alliomeria** [comment]
Hello @DiegoPino, pinging this [question @giancarlobi shared yesterday in the Archipelago slack](https://archipelagocommons.slack.com/archives/C01MNRS6LTG/p1658407712828439): "about using AMI (v 0.4.0) to update (replace) current ADO JSON: theoretical I can have a CSV with only two columns node_uuid and myvaluetoupdate. So, why AMI form ask me as required to map label?" 

Can the requirement for label mapping be removed for Update operations?

**Comment by aksm** [comment]
Resolved by f57b7c28ef20aa348c43b3e02dde503a6f6628c8.
