### ISSUE TITLE
Duplicate file associations from failed update ingests

### ISSUE THREAD

**Issue by patdunlavey** [esmero/ami#113]
We have found that when an AMI update ingest that is attaching files to objects is run multiple times, multiple file associations get created in the json to the same fid, but to different file entity uuids (urn:uuid, dr:uuid). And only one of those managed file entities actually exists. Here's an illustration from an actual object that has three file associations for the same file:
```
"as:audio": {
    "urn:uuid:13a671e9-53b0-41cb-b3c8-1d85e19beff6": {
        "url": "s3:\/\/media\/calajhs_000001\/calajhs_000001_access.m4a",
        "name": "calajhs_000001_access.m4a",
        "tags": [],
        "type": "Audio",
        "dr:fid": 177589,
        "dr:for": "obj_audio_files",
        "dr:uuid": "13a671e9-53b0-41cb-b3c8-1d85e19beff6",
        "checksum": "a19b543304b9dbc9a88c0b514c40fcd2",
        "flv:exif": {
            "FileSize": "132 MiB",
            "MIMEType": "video\/mp4"
        },
        "sequence": 1,
        ....
    },
    "urn:uuid:74995872-3788-4353-99f2-bd8e5f07da97": {
        "url": "s3:\/\/media\/calajhs_000001\/calajhs_000001_access.m4a",
        "name": "calajhs_000001_access.m4a",
        "tags": [],
        "type": "Audio",
        "dr:fid": 177589,
        "dr:for": "obj_audio_files",
        "dr:uuid": "74995872-3788-4353-99f2-bd8e5f07da97",
        "checksum": "a19b543304b9dbc9a88c0b514c40fcd2",
        "flv:exif": {
            "FileSize": "132 MiB",
            "MIMEType": "video\/mp4"
        },
        "sequence": 2,
        ...
    },
    "urn:uuid:a5127716-20ea-4bd0-9f7f-42d3c4706ba0": {
        "url": "s3:\/\/media\/calajhs_000001\/calajhs_000001_access.m4a",
        "name": "calajhs_000001_access.m4a",
        "tags": [],
        "type": "Audio",
        "dr:fid": 177589,
        "dr:for": "obj_audio_files",
        "dr:uuid": "a5127716-20ea-4bd0-9f7f-42d3c4706ba0",
        "checksum": "a19b543304b9dbc9a88c0b514c40fcd2",
        "flv:exif": {
            "FileSize": "132 MiB",
            "MIMEType": "video\/mp4"
        },
        "sequence": 3,
        ...
    }
},
```
However, the file_managed table only matches one of them:
```
root@868a54f815bc:/var/www/html# drush sqlq 'select * from file_managed where fid = 177589'
177589  13a671e9-53b0-41cb-b3c8-1d85e19beff6    en      9143    calajhs_000001_access.m4a       s3://media/calajhs_000001/calajhs_000001_access.m4a     audio/mpeg      138362563       1       1659038662      1659038676
```
My assumption is that the two file associations that do not use the `13a671e9-53b0-41cb-b3c8-1d85e19beff6` uuid, are the incorrect ones (I verified that they do not match any managed file in the database), and can simply be deleted from the json, probably after ensuring that the `sequence` value makes sense.

But I'd prefer that this not occur in the first place. We're seeing these when the first attempt to ingest an AMI update set fails and is re-run. However it's a mystery to me how, in that case, the invalid file associations could have all the file metadata (exif, etc), and why they would be sequence 2 and 3, rather than 1 and 2.

I'm guessing that the place this happens is in [strawberryfield\EventSubscriber\StrawberryfieldEventPresaveSubscriberAsFileStructureGenerator::onEntityPresave](https://github.com/esmero/strawberryfield/blob/1.0.0/src/EventSubscriber/StrawberryfieldEventPresaveSubscriberAsFileStructureGenerator.php#L126)?

**Comment by DiegoPino** [comment]
Fixed via https://github.com/esmero/ami/commit/4eee4c7726b1e8cc05a953b4f641c67e7c8bb3ae

**Comment by patdunlavey** [comment]
Thanks for pushing out this fix, @DiegoPino. It's really cool to come back from vacation and useful stuff has been done! Magic!

I agree about the missing part - I don't see how the failure is happening either. But your fix -- setting the uuid from the existing file -- seems like it should work. We'll be deploying and testing this and will let you know anything we learn (which, hopefully, will be that it works perfectly!).

**Comment by DiegoPino** [comment]
So happy you had some time off and hope this week starts slow and mild on work. Let me know if you find any other issues. I think File Management will need more and more work as we move into 1.1.0 and beyond, metadata seems to be at least a thing we got well done. Thanks a lot for reporting this
