### ISSUE TITLE
AMI now requires Drupal core ^9.3

### ISSUE THREAD

**Issue by patdunlavey** [esmero/ami#122]
In [AmiUtilityService.php, line 692](https://github.com/esmero/ami/blob/0.5.0/src/AmiUtilityService.php#L692) we see this reference to `Drupal\file\FileInterface::STATUS_PERMANENT`. However this constant does not exist in Drupal core until 9.3. 

I believe the solution is either to...
1. Change composer.json [here](https://github.com/esmero/ami/blob/0.5.0/composer.json#L16) to require `"drupal/core": "^9.3",`
2. Figure out an alternative to using this constant.

**Comment by DiegoPino** [comment]
@patdunlavey 9.2 is no longer maintained. Please feel free to make a pull to make ^9.4 required at the module level, if possible for every module
