### ISSUE TITLE
For transcripts and HOCR: fetch more datastream references to I7 Solr Importer

### ISSUE THREAD

**Issue by alliomeria** [esmero/ami#127]
# What is needed?

Check for + fetch additional datastreams for I7 Solr importer:
- for FULL_TEXT and TRANSCRIPT datastreams
- for HOCR datastreams
- for all the [MULTICHILDREN_CMODELS](https://github.com/esmero/ami/blob/8060cbe130d2e9bc4fed06219c1566ac19ea0ca2/src/Plugin/ImporterAdapter/SolrImporter.php#L38)
- generate URLs in 'texts' file column

👀 @DiegoPino , @karomabiles

**Comment by DiegoPino** [comment]
Also. Right now we only get PDF if OBJ is empty. You want always both?

**Comment by DiegoPino** [comment]
And another question... still get FULL_TEXT and TRANSCRIPT even if no OBJ?

**Comment by DiegoPino** [comment]
Should not be common at all. But I don't want to make files invisible to you. Always easier to remove a column than miss the fact you have files right?

**Comment by DiegoPino** [comment]
HOCR (only bc OCR is basically HOCR removing the XML). I think I will add it here too. Might be needed and we can discuss if/how that needs to be processed or when to remove the column at all

**Comment by karomabiles** [comment]
Would it be easier to get both now and test out scenarios, such as the one @alliomeria mentioned above with ADO to View Mode and Display mappings?

**Comment by alliomeria** [comment]
Ok, issue title & description updated to reference HOCR as well. Sounds good about fetching all-the-things. 😊✨

**Comment by DiegoPino** [comment]
See https://github.com/esmero/ami/pull/123/commits/d684382a2f17d67e52a9cda618eed7cb53fc18cf

**Comment by DiegoPino** [comment]
Resolved via https://github.com/esmero/ami/commit/d684382a2f17d67e52a9cda618eed7cb53fc18cf
