### ISSUE TITLE
Undefined array key "#description_display"  in Ami Row Preview Controller

### ISSUE THREAD

**Issue by DiegoPino** [esmero/ami#136]
Seeing this every time we run a preview in the logs

```Warning: Undefined array key "#description_display" in template_preprocess_form_element() (line 486 of /var/www/html/web/core/includes/form.inc)```

This seems to be related to a new key/required adding in recent Drupals. A few other modules seeing the same error e.g
https://www.drupal.org/project/migrate_tools/issues/3272434

Has anyone else seen this? @patdunlavey @alliomeria @aksm in your logs?
Fix is simple. Adding a pull now

**Comment by aksm** [comment]
@DiegoPino Seeing the same here in my logs.

**Comment by DiegoPino** [comment]
@aksm can you please test https://github.com/esmero/ami/pull/137 and see if after that the errors are gone? Or I am still missing something? Thanks

**Comment by DiegoPino** [comment]
Fixed via https://github.com/esmero/ami/commit/6f83eba728ca692f83df4f4faf955c43c8fbeb10
