### ISSUE TITLE
Cap the File URL to 255 chars

### ISSUE THREAD

**Issue by DiegoPino** [esmero/ami#138]
# What?

Happens that some users do have super long extra long filenames. Because of our needed file saving strategy during AMI ingest which involves a "temporary://" plus "amiset" plus the set id, plus md5 hash of the URL where we are fetching the file, even if the remote was already capped to 255 (e.g coming from Fedora) we are exceeding the Drupal 9 File Entity Limit for an URI field., BAD.

Idea (thanks to @alliomeria): I will cap the file name to the 255 characters but not from the beginning or the end (but a third secret option), from the center and add a set of character to fill up the space.

More over I will try, as much as possible to keep the original Filename (another Field in Drupal's file entity) intact since I won't have to add the URL part there. How?

By tapping into the actual saving mechanism instead of the download one.

Wish me luck

**Comment by alliomeria** [comment]
🍀

**Comment by DiegoPino** [comment]
Solved via https://github.com/esmero/ami/commit/93e32868a07d0793791334f32f3fde0a4832b4c5
