### ISSUE TITLE
Add alternate mimetype mappings

### ISSUE THREAD

**Issue by alliomeria** [esmero/ami#147]
## What's needed?

Add alternate mimetype mapping for standard (correct) extension for incorrectly classified source files (ie, currently .bin -> 'application/octet-stream' for image files with older/nonstandard 'image/jpg' mimetype in original exif info; same case for 'image/tif' potentially). 

Related to #108. As reviewed and discussed with @DiegoPino. 🤓

**Comment by DiegoPino** [comment]
The fix (to be sure) needs to happen both on strawberryfield adding the bad mappings (to intercept none AMI ingests) but also hardcoded in the AMI remote fetcher so we actually correct the bad mime types. Thanks @alliomeria 🎖️

**Comment by alliomeria** [comment]
Thanks to you @DiegoPino!

**Comment by DiegoPino** [comment]
Fixed everywhere, source and here. Also overriding MIME Types was a work around for islandora. Should not be needed In the future
