### ISSUE TITLE
Improve/fix AMI set Access Control/Permissions for AMI Set lists, Operations, etc

### ISSUE THREAD

**Issue by DiegoPino** [esmero/ami#151]
# What?

@alliomeria discovered that our Route access are too restrictive for AMI Set lists and also that the operations shown in the List once that is fixed don't match the permissions.

This requires (@alliomeria did this, credit) a change in the Routing to `view amiset  ..` 
Plus a change in the access Controller to treat 'edit' and 'update' as the same
Plus this change here

```PHP
public function getOperations(EntityInterface $entity) {
    $operations = parent::getOperations($entity); // TODO: Change the autogenerated stub
    if ($entity->access('process') && $entity->hasLinkTemplate('process-form')) {
      $operations['process'] = [
        'title' => $this->t('Process'),
        'weight' => 11,
        'url' => $this->ensureDestination($entity->toUrl('process-form')),
      ];
      if ($entity->access('process') && $entity->hasLinkTemplate('report-form')) {
        $operations['reports'] = [
          'title'  => $this->t('Report'),
          'weight' => 11,
          'url'    => $this->ensureDestination($entity->toUrl('report-form')),
        ];
      }
      // If applicable to the AMI Set, add the delete processed ADOs operation.
      if (AmiUtilityService::checkAmiSetDeleteAdosAccess($entity) && $entity->access('deleteados') && $entity->hasLinkTemplate('delete-process-form')) {
        $operations['delete_processed'] = [
          'title' => $this->t('Delete Processed ADOs'),
          'weight' => 12,
          'url' => $this->ensureDestination($entity->toUrl('delete-process-form')),
        ];
      }
    }
    return $operations;
  }
```
on the `amiSetEntityListBuilder.php  `

**Comment by alliomeria** [comment]
Hello @DiegoPino, I have the changes in a local fork created from the current 'main' branch. Should I create a PR against the main? Or add another local fork created from 0.5.0 and create a PR against that instead? Thank you!

**Comment by DiegoPino** [comment]
Hola @alliomeria please create a pull request from a local fork based on 0.5.0 against this upstream on 0.5.0. Thank you very much

**Comment by DiegoPino** [comment]
Resolved via https://github.com/esmero/ami/commit/c1971bae7c0794ee3a40995bf223b4851aa0315c by @alliomeria

**Comment by alliomeria** [comment]
Resolved with your help @DiegoPino! :) Thank you again!
