### ISSUE TITLE
file_save_data removed in Drupal 10

### ISSUE THREAD

**Issue by aksm** [esmero/ami#169]
# What?

Specifically in `AmiUitilityService.php`. Not sure if it's present anywhere else yet.

> Deprecated:
in drupal:9.3.0 and is removed from drupal:10.0.0. Use \Drupal\file\FileRepositoryInterface::writeData() instead.

**Comment by DiegoPino** [comment]
@aksm we have a few deprecations all around. Good time before release to deal with these. Check where else we have this one and we go from there. We can start with core https://api.drupal.org/api/drupal/deprecated/10
and I also know all search_api_solr hooks need to be moved to events (I got that part)

**Comment by DiegoPino** [comment]
Sorry this list is more pressing for core https://api.drupal.org/api/drupal/deprecated/9

**Comment by DiegoPino** [comment]
Resolved via https://github.com/esmero/ami/commit/05d6a5bb7a7860b7d05eae25eb04d1219ec258d0
