### ISSUE TITLE
Metadata Preview AMI set for Add Metadata Display

### ISSUE THREAD

**Issue by aksm** [esmero/ami#180]
# What?
Currently, checking an AMI set via Metadata Display Preview requires editing an already saved Metadata Display template. When adding a new template the option for AMI Sets is not available.

It looks like all that's required is to change the following:

https://github.com/esmero/ami/blob/bceee5d1902c9104dc89c6d97b26665d67d7f419/ami.module#L36

to:
```php
function ami_form_metadatadisplay_entity_form_alter(&$form,FormStateInterface $form_state, $form_id)
```

**Comment by DiegoPino** [comment]
@aksm means adding extra, or just changing? Thanks for catching this one!

**Comment by aksm** [comment]
> @aksm means adding extra, or just changing? Thanks for catching this one!

@DiegoPino Just changing. The base form hook covers both.

**Comment by DiegoPino** [comment]
Ok, but the `delete` one will have a preview then? mmmmm so maybe it needs internal a check of which form is using it?

**Comment by aksm** [comment]
> Ok, but the `delete` one will have a preview then? mmmmm so maybe it needs internal a check of which form is using it?

@DiegoPino Just checked and the delete form isn't altered by the base form hook.

**Comment by DiegoPino** [comment]
ok, cool. thx!

**Comment by DiegoPino** [comment]
Solved
