### ISSUE TITLE
Support group entities as ADO parents

### ISSUE THREAD

**Issue by patdunlavey** [esmero/ami#20]
The [group](https://www.drupal.org/project/group) module provides the ability associate content with groups, and ability to constrain create, update, view and delete access of/to group digital object content based on the user's membership in a group. In short, we want to use groups like archipelago collections.

The relationship between groups and their content is mediated by the group module through group membership entities - there is no "awareness" in the content itself of its membership in the group. 

For manual ADO creation, I think this will "just work": the user (group member) creates an ADO as group content, just as they would for conventional nodes. 

However, with AMI, we need to be able to create this relationship as ADOs are created, and modify that relationship as ADOs are updated.

**Comment by patdunlavey** [comment]
Presumably, the relating of ADOs to groups would be handled in an event handler that responds to the ADO being created or updated. This may be best done in a small separate module `strawberryfield_group`. Presumably, this would be done using the `parent` uuid. However, we need a way to communicate to this event handler that we want to create a relationship to a group.  That the event include the information, something like, "$ado->parent_entity_type = 'group'". AMI needs to have a way to know that this `parent` entity is a group. Simply providing the UUID is not sufficient, since you cannot load an entity given just the UUID - you also need the entity type.

Some ideas:
  1. Support prefixing the UUID in the `parent` column with the entity type. E.g. `group:1234-5678-90as-dfgh-hjkl`. This would require, at a minimum, something like this in AMI:
  ```php
$parent_uuid_parts = explode(":", $parent_uuid);
$parent_uuid = array_pop($parent_uuid_parts);
$parent_entity_type = count($parent_uuid_parts) > 0 ? array_pop($parent_uuid_parts) : 'node';
...
   ```
  2. Create one or more alter hooks in AMI that permit another module to inject the logic that ends up providing the entity type to the create/update ADO event handler.

**Comment by DiegoPino** [comment]
@patdunlavey for sure. Please close and thanks. Would love if you could (someday) explain your approach using groups. It may beneficial of other community members. Cheers!

**Comment by DiegoPino** [comment]
Closing since it seems the discussion lead to closing
