### ISSUE TITLE
make sure `ap:tasks` are not overridden by our standardized defaults when updating via an AMI update via replace operation

### ISSUE THREAD

**Issue by DiegoPino** [esmero/ami#200]
# what?

The moment in time, when we check/set the basic required `ap:task`json fields during an AMI Set Update operation is too soon for a "replace" operation. Most replace operations won't have that key at all defined and because we check if they need to be "normalized" on the output of a direct/replace action before we merge back to the whole ADO, we end removing manually set nested keys/values, like the one that allows another label key to be used for node title or even the "not run this SBR processor"

@alliomeria this is what you correctly diagnosed today. Thanks for debugging that. I will fix this. Sorry for the hiccup

**Comment by alliomeria** [comment]
Thank you for reviewing this together with me live today, and confirming the current setup. Thank you also for making this issue and adjusting where the `ap:tasks` are being checked + set. :)

**Comment by DiegoPino** [comment]
Resolved via https://github.com/esmero/ami/commit/0dda14a4210edbbcd742863d16f7c616e8d8238b
