### ISSUE TITLE
Error on "drush updb" with getOption() on Null

### ISSUE THREAD

**Issue by roromedia** [esmero/ami#207]
If Layout Builder module is disabled  "drush updb" fails with getOption() on null error in Line 93 here:
https://github.com/esmero/ami/blob/5c1e864a12e5ca6cc11792ae4be0fa795b34323b/src/EventSubscriber/AmiFacetsViewsBulkOperationsEventSubscriber.php#L93
There should be some check for the Layout Builder to mend that.

**Comment by DiegoPino** [comment]
@roromedia if you could confirm #206 fixes the problem so I can merge, that would be great. If not I can put more work on it.

**Comment by DiegoPino** [comment]
Fixed via https://github.com/esmero/ami/commit/f9d012e7ef563df4f909db3c14b4ba20eaac6e94
