### ISSUE TITLE
CSV expander queue worker fails to generate ADO ingest update queue items when run from cron or hydroponics

### ISSUE THREAD

**Issue by patdunlavey** [esmero/ami#214]
The reason is because, when running under cron and AmiUtilityService::preprocessAmiSet() is called from... https://github.com/esmero/ami/blob/f9d012e7ef563df4f909db3c14b4ba20eaac6e94/src/Plugin/QueueWorker/CsvADOQueueWorker.php#L90
... the current user is anonymous (0), and as a result the access check...
https://github.com/esmero/ami/blob/f9d012e7ef563df4f909db3c14b4ba20eaac6e94/src/AmiUtilityService.php#L1842
... fails.

After discussion on [slack](https://archipelagocommons.slack.com/archives/C01A4MPFQA0/p1724954795386759), we agreed that it made sense to replicate the logic from... 
https://github.com/esmero/ami/blob/f9d012e7ef563df4f909db3c14b4ba20eaac6e94/src/Plugin/QueueWorker/IngestADOQueueWorker.php#L1188-L1192
... where the access check is performed using the user account provided in the AMI set.

PR forthcoming!

**Comment by DiegoPino** [comment]
@patdunlavey thanks for opening this. Fixed via 
https://github.com/esmero/ami/commit/bfdb7c531d10058ad84e426db9b329ea5a5cc95a
and
https://github.com/esmero/ami/commit/567fea5a1e3fa68d70fa41a36a9c57751f08e821

Thanks for your contribution!
