### ISSUE TITLE
Google sheet import failing due to autoload failure

### ISSUE THREAD

**Issue by patdunlavey** [esmero/ami#24]
We're suddenly having this problem with Google Sheet import. After filling in the Google Sheet ID and cell range and clicking "Next", nothing happens. Watchdog reports...
```
Error: Class 'Google_Service_Adsense_Resource_Accounts' not found in Google_Service_Adsense->__construct() (line 67 of /var/www/html/vendor/google/apiclient-services/src/Google/Service/AdSense.php)
#0 [internal function]: Google_Service_Adsense->__construct(Object(Google\Client))
#1 /var/www/html/web/modules/contrib/google_api_client/google_api_client.module(135): ReflectionClass->newInstance(Object(Google\Client))
#2 /var/www/html/web/modules/contrib/google_api_client/google_api_client.module(60): _google_api_client_read_scope_info()
#3 /var/www/html/web/modules/contrib/google_api_client/src/Entity/GoogleApiClient.php(179): google_api_client_google_services_scopes(Array)
#4 /var/www/html/web/modules/contrib/ami/src/Plugin/ImporterAdapter/GoogleSheetImporter.php(176): Drupal\google_api_client\Entity\GoogleApiClient->getScopes()
#5 /var/www/html/web/modules/contrib/ami/src/Form/AmiMultiStepIngest.php(393): Drupal\ami\Plugin\ImporterAdapter\GoogleSheetImporter->getData(Array, 0, -1)
#6 [internal function]: Drupal\ami\Form\AmiMultiStepIngest->submitForm(Array, Object(Drupal\Core\Form\FormState))
```
When I remove the vendor folder and run `composer install`, composer reports that it is skipping autoload generation for a bunch of Google_Service_Adsense classes due to non-compliance with psr-0 autoloading standards.

**Comment by DiegoPino** [comment]
@patdunlavey can you share your composer info for the related libraries? Are you using our composer.lock or going wild out and updating globally packages? Or maybe you missed updating one the the classes.

Also composer --version ??

composer will complain about this libraries if  "optimize-autoloader or classmap-authoritative are enabled" but composer 2 has this solved.

**Comment by DiegoPino** [comment]
@patdunlavey is this still an issue?

**Comment by dmer** [comment]
I'm going to answer for Pat that this is now working -  I believe that getting composer versions sorted out did the trick

**Comment by patdunlavey** [comment]
Yep. Closing.
