### ISSUE TITLE
File ordering/sequencing options

### ISSUE THREAD

**Issue by alliomeria** [esmero/ami#25]
# What is needed?
Provide additional file ordering/sequencing options for source files in AMI.

Options below resultant from recent discussions on the #archipelago-metadata slack channel:

1. Files ingested via a URL source will always sort by the order listed within the cell. (help text on the AMI configuration step will let users know this is the case?)

2. If users select Direct or Template during Step 3:
     - All files will be sorted by natural order by filename.

3. If users select the “Custom (Expert Mode)” during Step 3:
     - For each type of ADO found in a spreadsheet/import source, users will have an option to specify that file sorting respects the order given in the cell. Selecting this will add a flag of “user provided order for referenced filenames” (or similar phrasing)
     - If users do not select the option to specify by order given in the cell, then files will be sorted by natural order by filename

## Devnotes :strawberry::
- the “respect ingest/cell order” option will add a flag ; this flag will persist on manual edits; if the flag is absent, files will be ordered by filename (and/perhaps a message with order by sequence in cell)

@DiegoPino & @giancarlobi, does this match your understanding of the options discussed? If not, please let me know and I will correct these issue notes. Thank you both!

**Comment by DiegoPino** [comment]
Excellent! Thanks so much

**Comment by DiegoPino** [comment]
ap:tasks solves this. Closing
