### ISSUE TITLE
Allow AMI Sets to be used for Metadata Display Preview

### ISSUE THREAD

**Issue by alliomeria** [esmero/ami#28]
# What is needed?
Provide ability for AMI Sets to be used for Metadata Display Preview

## Why?
So users can review and refine their AMI JSON Ingest Template(s) while referencing an AMI Set

**Comment by DiegoPino** [comment]
@alliomeria great!

This is going to be a Form Alter from AMI. IT will add an AMI autocomplete + a ROW selection (which row to test) and then will also alter the TWIG context to "push" that data into the twig template. Its going to be AWESOME!

**Comment by DiegoPino** [comment]
Implemented and fixed.
