### ISSUE TITLE
google_api_client error

### ISSUE THREAD

**Issue by patdunlavey** [esmero/ami#30]
When visiting /admin/config/services/google_api_client (Google Accounts administration), several warnings are displayed, which stem from the first:

`Warning: scandir(/var/www/html/vendor/google/apiclient-services/src/Google/Service/): failed to open dir: No such file or directory in _google_api_client_read_scope_info() (line 113 of modules/contrib/google_api_client/google_api_client.module).`

And if I try to edit or add a google api client account, a wsod appears, with the following error message:

```
The website encountered an unexpected error. Please try again later.
TypeError: Argument 1 passed to Drupal\Core\Form\OptGroup::flattenOptions() must be of the type array, bool given, called in /var/www/html/web/core/lib/Drupal/Core/Field/Plugin/Field/FieldWidget/OptionsWidgetBase.php on line 187 in Drupal\Core\Form\OptGroup::flattenOptions() (line 23 of core/lib/Drupal/Core/Form/OptGroup.php).
```
I confirmed that the /var/www/html/vendor/google/apiclient-services/src/Google directory does not exist. The `src` directory does, and contains a number of other directories. Removing the vendor directory and re-running composer install does not restore the missing `src/Google/Service` directory. 

I noticed that the most recent version of google_api_client is 4.0.0, and tried switching to that in archipelago-deployment's composer.json, however, the ami module's composer.json also requires this module, and also specifies its version as ^3.0. So I tried changing the version numbers to `^4.0` in composer.json for both ami and archipelago-deployment (what I actually had to do was much more complicated than that, but that's the gist) - and quickly ran  into autoload.php and composer hell. After trying a few things like uninstalling and reinstalling, clearing cache, etc., I backed away slowly.

However I did find that when I manually made a change to the hard-coded path in google_api_client.module to the path that's used in the 8.4.x version of that module, then the errors went away everything seemed to work. [Here's that change](https://git.drupalcode.org/project/google_api_client/-/commit/5aa67797c37e8db1309604c5323bb3de15117db4#9e0530adbf0fd562b79cea9b5c63d91d1d7d238c_112_112).

**Comment by DiegoPino** [comment]
@patdunlavey sorry for the delay. I'm out of the office these days. These seems to be a mismatch of the required libraries.
google_api_client: 4.0.0 is made to support this core google api client PHP service.
https://github.com/googleapis/google-api-php-client-services/releases/tag/v0.201.0

While google_api_client:3.2 (or ^3.0) is using v0.174.0, set by our composer.lock

https://github.com/esmero/archipelago-deployment/blob/1.0.0-RC2/composer.lock#L7609-L7616

I think there is an issue here on how composer update  (or the require -W) was applied but can not blame anyone (may be the module maintainer, people test so little lately in Drupal modules) or google api. But one thing I can do is (next week) Monday? work with you on some `Composer` workflows and tricks so you do not end with broken installations (whatever you do, autoload.php and composer hell should never happen with these "tricks") but also when a module like this one changes and you want to update, you can. Composer **has not made** upgrading/maintaining Drupal easier. That is a fact.

Sadly I can not make google_api_client dependency a generic one inside AMI, I need and 3.2 to 4.0 is a mayor version change and 4 has not been tested on our side yet.

In the meantime, I can check 4.0, test, setup and if all goes fine, update the dependency for AMI 0.2.0 to  ^4.0 and document for you how to update without errors not patching.

let me know if you want to meet next week. Hugs

**Comment by patdunlavey** [comment]
This magically fixed itself. Closing!
