### ISSUE TITLE
"Webform based find and replace Metadata for Archipelago Digital Objects content item" bulk operation does nothing

### ISSUE THREAD

**Issue by patdunlavey** [esmero/ami#32]
This feature appears to work great right through the configuration, confirmation and execution steps, but in the end, no changes are made to the selected objects.

From @DiegoPino on slack:

> I think i have an idea to get around the issue
> basically using a Contextual bar (like we do for the twig preview) with the form there (so outside of the form that VBO provides) that sets a temp value into a tempstore
> and is picked then by the actual vbo form on submit later
> issue there is that the VBO config form is already wrapped around another one i have no control over
> so i can not make it “super dynamic” as i would like to

**Comment by DiegoPino** [comment]
@patdunlavey will do!

**Comment by DiegoPino** [comment]
This is work since 0.3.0. Closing as fixed
