### ISSUE TITLE
Ingesting large media files from AWS S3 fails

### ISSUE THREAD

**Issue by patdunlavey** [esmero/ami#38]
We're testing ingesting objects via AMI that have multiple large media (video, audio) files attached to them which are stored on AWS S3. These frequently fail. When they do...

- If processing via immediate batch, the batch stops and displays an ajax error message indicating a gateway timeout: 
![Screenshot from 2021-10-13 13-56-21](https://user-images.githubusercontent.com/241240/137187439-cfefac37-e77f-4625-a069-332b080ebc4b.png)
- If processing via batch queue and the batch is manually run, we see a "Sorry we did all right but failed created the ADO with..." message:
![Screenshot from 2021-10-13 13-58-58](https://user-images.githubusercontent.com/241240/137187705-38f37588-bd6f-4e7a-ad2c-15d4e2a1b672.png)

We found that having the files in the local file system seems to work without problems. We're thinking that something is timing out, possibly while fetching the files from AWS S3. These are large-ish files. In one of our test examples, it's six video files totaling over 3GB.

We find no "smoking gun" in either the drupal logs or php logs. 

I recognize that this may not be an AMI issue per se, but that's where we're encountering the problem.

**Comment by patdunlavey** [comment]
We're going to test adjusting default_socket_timeout (currently at 60 seconds). Additionally, [this stackoverflow comment ](https://stackoverflow.com/a/34040761/15291506) suggests setting fastcgi_read_timeout, which I'm not sure is applicable but we'll look into it.

**Comment by DiegoPino** [comment]
@patdunlavey let me know how that goes. You may want to aim at 300 seconds or more. 
One idea I have been digesting in the last 2 days would be to make the actual File processing an extra (or many) extra subtasks (queue entries). That way each piece could have its one time. Will explore that idea a bit deeper but won't be for 1.0.0 sadly.

**Comment by DiegoPino** [comment]
@patdunlavey you want to check the latest pull/fix made which makes default_socket_timeout not needed since it uses now 75% of the PHP Time to live and also respects metadata like original File Name (e.g from Islandora)

**Comment by patdunlavey** [comment]
We're working on putting a pair of movie files in a public location. They're 1.2 gb, and the upload is slow. I'll let you know when they're up.

**Comment by DiegoPino** [comment]
Thanks

Diego Pino Navarro
Assistant Director for Digital Strategy
Archipelago architect
Metropolitan New York Library Council
PO Box 2084
New York, NY 10108

**Comment by patdunlavey** [comment]
Two movie files and one xml:
- s3://bd-archi-demo-content/CAR/calauem_000189_t01_access.mov
- s3://bd-archi-demo-content/CAR/calauem_000189_t02_access.mov
- s3://bd-archi-demo-content/CAR/calauem_000189_PBCore.xml

Here's the corresponding csv for illustration purposes:
[9143-622f91d19558b2.csv](https://github.com/esmero/ami/files/8365574/9143-622f91d19558b2.csv)

**Comment by patdunlavey** [comment]
Super good news! It seems that this problem can be fixed by increasing nginx's fastcgi_read_timeout setting. In my case, increasing it from 120s to 720s, and using individual file queueing, enabled the AMI Set that had been failing every time to succeed. 

An interesting additional bit of intel about this behavior: After attempting to ingest and then update the first time, I got the usual 504 error during the update (with individual file queueing enabled). But when I re-ran the update ingest (again with file queueing enabled), it processed in seconds, and the movie file was there.  My theory is that the gateway timeout happens during the s3 file fetch, but it doesn't actually stop the fetch. The fetch itself eventually succeeds. But the gateway timeout crashes any activity that's supposed to happen subsequent to the file fetch. When using the file queueing option, file fetch metadata is saved, including information about where the temporary file is being locally stored. This prevents re-downloading the file if you re-run the ingest. Then when the ingest was re-run, the file was already there, ready for mediainfo to run and complete the ingest. And bingo! It works.

I propose that we close this as an AMI issue, and open issues to write documentation for the archipelago-deployment repos, and the documentation repo. I'd keep it as an AMI issue to write something in the AMI readme file, but since there's nothing at all there at the moment, that doesn't really make any sense.

**Comment by DiegoPino** [comment]
Good! Closing it! Thanks so much
