### ISSUE TITLE
free dates with edtf "[<dates>]" syntax (one or more dates in square brackets) are saved as json arrays rather than original strings

### ISSUE THREAD

**Issue by patdunlavey** [esmero/ami#40]
One of EDTF's features is "Set representation", which permits listing several dates enclosed in square brackets or curly braces. date_free values that use set representation are being json_decoded by AMI and saved into the date_free json value as an object or an array, rather than as a string. 

I tried a number of tricks in the twig template to (e.g. using `escape('js')` to get AMI to treat them as strings, however nothing I tried worked - either having the free date saved as an array/object, or throwing an error: "We could not generate JSON via Metadata Display with..."

Digging around in AmiUtilityService.php:1954 I see that AMI is sending json_decoded data to the twig template, which I guess makes sense. 

I tried this in my template:
```
"date_free": {% if data.my_field is iterable %}"{{ data.myfield|json_encode|raw }}"{% else %}{{ data.myfield|json_encode|raw }}{% endif %}
```
Note that the only difference is that the first iterable version wraps the json encoded value in quotes, while the second relies on json_encode doing the quotes.

I'm not actually sure if this worked as intended - not sure if `is iterable` is the right test here. At any rate, that's as far as I got, and it didn't work.

I'm not sure if this is an actual bug, or if I'm just not doing my twig right. Thoughts @DiegoPino ?

**Comment by DiegoPino** [comment]
Hi friend, sorry you are fighting Archipelago! For Archipelago the world is JSON! 

If you need the "textual/single string" representation of ["something"] and not a JSON decoded representation of ["something"] then you need to escape your `["something"]`. e.g have you tried `\[\"date\"\]` or something in that realm?

The code that tries to do JSON out of anything that looks like JSON is here


https://github.com/esmero/ami/pull/31/files#diff-aa7543ef3888460c067a0c879d9166035120b2788ae7f737a0fd860e8cf64555R1741-R1783

I can make an example for you but you can also do some Twig template testing by enforcing the value into a fake variable 
{% set my_edtf = "\[\"date\"\]" %}
and then put that into your JSON and see how that looks.

Hope that helps

**Comment by DiegoPino** [comment]
Oh, also. Let's say your users do not want to escape their data that looks like JSON and archipelago needs to treat like json.
Replace your [] characters with anything that is not in the JSON vocab/protected world
And then, In the twig template itself, for that column replace the used characters, let's say `|` for  the escaped `[` and done. happy users, you have full control.

**Comment by DiegoPino** [comment]
@patdunlavey another take (being generous today but also a bit tired to bare with me)

Let's say you left archipelago simply deal with the decoding and do not make any changes

Then on the twig template you may have an array (as you discovered)

Try this (simulating the value just to try)
```
{% set my_field = ["somedate"] %}
{% set my_field2 =  my_field|json_encode|json_encode %}
{# now output this #}
"date_free": {{ my_field2|raw }},
```
Result will be
`"date_free":  "[\"somedate\"]",`
Do not try double json_encoding inside a print statement `{{ }}` because by default Twig will treat chained double encodings as a human error and will do it only once. (last time I checked I might be wrong)

Your `is iterable` check is good

**Comment by DiegoPino** [comment]
@patdunlavey uff, more of me.

Are you sure `[2021-20-20]` is becoming JSON with ISSUE-14 code? no double quotes... ?

**Comment by patdunlavey** [comment]
I thought Issue-14 had been merged! I assume that will happen before 1.0 release, i.e. "real soon now"?
As it happens, I have been using a branch on my local that has ISSUE-14 merged, but our deployed servers are using straight 0.2.0. That said, I'm not sure of the answer to your question - more behavioral testing needed. I'll also try the double-json_encoding.
Thanks @DiegoPino !

**Comment by patdunlavey** [comment]
Double json_encoding didn't work (got the could not create metadata error). Here's what did work (it expects any date free source field to be named like `something_date_free`:
```
function my_module_format_strawberryfield_twigcontext_alter(&$context) {
  foreach($context['data'] as $field => $data) {
    if(preg_match('/.*_date_free/', $field) && in_array(gettype($data), ['array', 'object'])) {
      $context['data'][$field] = json_encode($data);
    }
  }
}
```
I think this is a reasonable solution. Do you agree @DiegoPino? Shall I document it and offer a PR to the archipelago-documentation repo?

**Comment by DiegoPino** [comment]
@patdunlavey sorry, totally up to you if you want to hardcode an alter there but that would not make sense as docs for Archipelago because, a, we will not provide that hook, second that hook will add some performance penalty and I also tested all my suggestions and all works that here. Can you share a piece of your CSV or your Twig? Quite confused about why it does not work for you.  Give me a few, we are on release work.

**Comment by DiegoPino** [comment]
Closing this as solved since my Slack solution worked out. @alliomeria will add that solution as a default to AMI ingest template and to the Twig templating docs as an example.
