### ISSUE TITLE
Missing 'type' column, or missing values in the 'type' column, causes inscrutable errors when creating an AMI set

### ISSUE THREAD

**Issue by patdunlavey** [esmero/ami#50]
When an ingest spreadsheet is preprocessed during AMI set creation, if there is no "type" column, or if there are empty values in the "type" column, we see the error message "1 error has been found: Select the data transformation approach for ". The message is supposed to include the type, but since none exists, it looks like this. Further configuration of the AMI set is not possible.

The behavior should be that it provides an error message saying that a "type" column with values is required. I'd also suggest that the "type" column itself be configurable, where you are presented with a list of all column names, and instructed to select one for the object type.

**Comment by DiegoPino** [comment]
Thanks Pat! Any pulls coming with this Issue?

**Comment by DiegoPino** [comment]
re:
>The behavior should be that it provides an error message saying that a "type" column with values is required. I'd also suggest that the "type" column itself be configurable, where you are presented with a list of all column names, and instructed to select one for the object type.

Sadly I will decline that use case, but open to consider if we have more people from other institutions asking the same (anyone?). Users have already enough config options and the UI is a bit too much already. Being able to set a "type" column mapping should be not too much to ask as a conditional and having it as a moving target might induce more User errors. having a type config will also add a lot of passing of configs around in places where we need to depend on that column in a fixed way.

**Comment by patdunlavey** [comment]
I'm not particularly impressed with this solution! https://github.com/esmero/ami/pull/51. I'm not familiar/comfortable with how to do actual validation on multi-step forms. It really should prevent moving to the next step.

**Comment by DiegoPino** [comment]
Solved by @patdunlavey via https://github.com/esmero/ami/commit/6639ceca26aa519110fe56bf189712e93d6671d9. Thanks @patdunlavey for your contribution!
