### ISSUE TITLE
AMI Solr Importer Plugin Suffix Cleanup

### ISSUE THREAD

**Issue by alliomeria** [esmero/ami#52]
# What is needed?

AMI already performs some clean up 🪄 of various commonly-encountered duplicative/redundant Solr fields with particular suffixes:
https://github.com/esmero/ami/blob/0bc76be41c19ecfcbec02959d7a0329b1ebe6468/src/Plugin/ImporterAdapter/SolrImporter.php#L36

Additional common prefixes that would also be helpful to include in this clean up:
- _t
- _mt
- _mlt

@DiegoPino, @aksm, and all Solr Importer fans, any other prefixes to consider for this process?

**Comment by DiegoPino** [comment]
@alliomeria will add this change to the Children/PID list improvement I'm doing too. Can't think right now of other prefixes, but maybe we can add an "advanced" tab to allow people to add more? Thanks so much

**Comment by alliomeria** [comment]
@DiegoPino @aksm I tested this in my local deployment, multiple batches (collapsed/uncollapsed, different collections), and all went well.

**Comment by DiegoPino** [comment]
Solved via https://github.com/esmero/ami/commit/c0f71691ff90d659488042c07582424369b68c49 by @alliomeria !! Thanks so much!
