### ISSUE TITLE
Fix/Research better VBO integration with Solr Search Results and faceted Views

### ISSUE THREAD

**Issue by DiegoPino** [esmero/ami#61]
# What?

[VBO](https://www.drupal.org/project/views_bulk_operations) is great but it is quite buggy. It has some strange ways of managing the List of Content Items to be processed and so far our experience is that it does not respect (specially when using the "Select All" button) the actual results the user is seeing on screen.

In specific for our need this view here: http://localhost:8001/search-and-replace (replace with your domain)
Needs to allow users to facet/filter, then select "All" and get actions applied to the actual UI facing set, which sadly does not work right now.
Only thing that works is there are exposed Filters (not facets) and the View is not Ajax Driven.

There are at least 2 mayor issues (also form a UI standpoint)

- `ViewsBulkOperationsActionProcessor` is the one in charge of getting the Views arguments or manual selections and build a list of Content Items to be processed. The way VBO works is that once the user selects an action it "recreates" the View Results (so does not depend on the initial results build, e.g via faceting) and uses also the /argument1/argument2 etc in the URL to feed Views Filters (which might not even be available if e.g the View is Ajax driven.  Even if you select all the "UI" text will say "No items selected"
- `Facets` which generate GET arguments like http://localhost:8001/search-and-replace?f%5B0%5D=descriptive_metadata_object_types%3ADigitalDocument and that are used by Search API when building the Views Result (query time by altering a View) are ignored once the Action is chosen because the form that drives the submit makes these disappear (does not preserve GET)

What we need is
- Figure out what is wrong and what can/can not VBO do. See also if VBO has managed to fix some of these issues at all on their releases
- Maybe (I feel that is the best idea really) create our own version of [`\Drupal\views_bulk_operations\Plugin\views\field\ViewsBulkOperationsBulkForm`](https://git.drupalcode.org/project/views_bulk_operations/-/blob/4.1.x/src/Plugin/views/field/ViewsBulkOperationsBulkForm.php) which is a `Views Field Plugin` but also the `Form` that drives basically all the submit/steps/etc logic, one that takes Facets in account, is smarter and also gives Users a better feedback on what is happening. I see that as the only possible point of "override we have". WE could also of course at a secondary submit handler to that existing form and enrich data by putting it into some key store values (VBO uses temp store extensively to move data between form steps), but we might end again having to override other classes anyway

Do we need some reproducible tests?

@alliomeria @patdunlavey @aksm @karomabiles

**Comment by patdunlavey** [comment]
I'm willing to take a stab at this in the next week or two.

**Comment by DiegoPino** [comment]
@patdunlavey assigned! happy to give you help/Support/share findings! You are the best!

**Comment by DiegoPino** [comment]
This is for my own notes:

- The best native way of doing this is to create a Facets Processor Plugin. Like this one
```PHP
namespace Drupal\facets\Plugin\facets\processor;

use Drupal\facets\Exception\InvalidProcessorException;
use Drupal\facets\FacetInterface;
use Drupal\facets\Processor\BuildProcessorInterface;
use Drupal\facets\Processor\PreQueryProcessorInterface;
use Drupal\facets\Processor\ProcessorPluginBase;

/**
 * The URL processor handler triggers the actual url processor.
 *
 * The URL processor handler allows managing the weight of the actual URL
 * processor per Facet.  This handler will trigger the actual.
 *
 * @FacetsUrlProcessor, which can be configured on the Facet source.
 *
 * @FacetsProcessor(
 *   id = "url_processor_handler",
 *   label = @Translation("URL handler"),
 *   description = @Translation("Trigger the URL processor, which is set in the facet source configuration."),
 *   stages = {
 *     "pre_query" = 50,
 *     "build" = 15,
 *   },
 *   locked = true
 * )
 */
class UrlProcessorHandler extends ProcessorPluginBase implements BuildProcessorInterface, PreQueryProcessorInterface {
```

That kicks in always BUT only alters the Views Query when/during a VBO Batch.

During a VBO action this temporary Storage is created

```
 $variable in \Drupal\views_bulk_operations\Plugin\views\field\ViewsBulkOperationsBulkForm::updateTempstoreData
      
      result = {array} [8]
       batch = true
       batch_size = {int} 50
       total_results = {int} 17
       relationship_id = "none"
       arguments = {array} [0]
       exposed_input = {array} [4]
       bulk_form_keys = {array} [17]
       redirect_url = {Drupal\Core\Url} [12]
```

Which fun for us, will contain (if we alter the Action Form to get the `f[]` arguments from the Rendered Views)
```
  exposed_input = {array} [4]
          f = {array} [1]
          f[0] = "descriptive_metadata_object_types:Photograph"
          search_api_fulltext = ""
          type_1 = ""
```

So, by using that structure, we can make the Query that will not be aware of an actual URL aware of the Facets passed.

Resuming:
-  Alter the Form so when the Views that is rendered has facets we add hidden fields with the `f[]` (that code is simple, done already for exposed forms In views -
- Write a Facet processor that runs at the end, that checks IF we are in the context of an active Batch (when the batch initializes)
and instead of getting the facets from the URL gets them from the temporary storage created by VBO. 


This took me good 24 hours to debug but I will try to get this done. This is a game changer for Search and Replace in Archipelago!

**Comment by DiegoPino** [comment]
@patdunlavey @alliomeria I got it! https://github.com/esmero/ami/pull/95

Took me Friday, Saturday and today (5 min ago) to get this working. This is really so needed. Hope you can give it a look soon. Will ask the Metro team to test next week. Very happy (and exhausted)

**Comment by patdunlavey** [comment]
This is super-exciting, @DiegoPino, what an accomplishment! I'll test as soon as I can. Can you or @alliomeria describe some sample tests for me to try?

**Comment by DiegoPino** [comment]
@patdunlavey will let you know tomorrow with instructions. Too many open pulls and more coming! Thanks!

**Comment by DiegoPino** [comment]
Solved via https://github.com/esmero/ami/commit/a08822f22f985397a5522c5e23d5b30dea53b788
