### ISSUE TITLE
Checkbox not rendering in LoD cleanup

### ISSUE THREAD

**Issue by aksm** [esmero/ami#62]
# What?
Checkboxes are not rendering in the form under `Edit Reconciled LoD` when editing an AMI set. Isolated to this custom element. Simple fix.

**Comment by DiegoPino** [comment]
@aksm can you please add longer description for future reference. This might come up again and only affects the custom element too. Thank!

**Comment by DiegoPino** [comment]
Resolved via https://github.com/esmero/ami/commit/c360cee6006425005a62f97a27296abdf6782066 by @aksm . Thanks
