### ISSUE TITLE
LoD Reconciliation Reuse / Iterative Workflow

### ISSUE THREAD

**Issue by alliomeria** [esmero/ami#69]
# What is needed?

Ability to reuse LoD Reconciliation data from other AMI Sets.
- in order to build upon, iterate over the metadata work completed previously 
- help ensure consistency of LoD mappings in your repository
- ♻️ reduce the collective energy footprint of metadata work lifecycles

# How might this work?

- On the 'Reconcile LoD' tab of your AMI Set, have an option to "Bring LoD from other AMI Set"
    - Dropdown (or autocomplete?) to select from existing AMI Sets
- Once your preferred Set is selected, option to "Bring as Checked"
    - If selected, will carry over the "Checked" connotation marked in the existing AMI Set, so you can reference if terms have already been reviewed previously
- Inline notes should indicate that if using LoD from an existing Set, only terms **new** to the **current** AMI Set will pass through reconciliation 

## For wider AMI workflow considerations
- When working in the 'Edit Reconciled LoD' tab of your Ami Set, have an option to Filter by Checked/Unchecked
- In the Processed LoD CSV, include a Notes column to include information about the AMI Set origination and date

@DiegoPino @karomabiles Does this cover what we all discussed for the potential reusable/iterative LoD workflow? Anything missing / not quite right?

**Comment by DiegoPino** [comment]
Resolved and implemented. LoD CSVs can be attached to existing AMIs, replaced, removed
