### ISSUE TITLE
AMI Could query IsMemberOf as well as IsMemberOfCollection

### ISSUE THREAD

**Issue by sfoleyham** [esmero/ami#82]
We have the i7 importer to create AMI sets.  Some of our collections have the legacy IsMemberOf and lack the IsMemberOfCollection in the RELS-EXT.  Could the importer please include both?

**Comment by DiegoPino** [comment]
@sfoleyham this will be pushed tomorrow morning. Testing now. thx

**Comment by DiegoPino** [comment]
Fixed via https://github.com/esmero/ami/commit/949d160a81e2fe9290315872655485063a15fa72
