### ISSUE TITLE
AMI set, Process immediately v/s enqueue, Questions

### ISSUE THREAD

**Issue by DiegoPino** [esmero/ami#9]
# What? This are questions for @alliomeria @giancarlobi @pcambra and @patdunlavey 

Each AMI set has a "process" tab/form. When you press process right now the only action that is happening is that all Future ADOs are enqueued, independently of the Set ID, into a global AMI Ingest Queue. This queue can then be processed via the UI if the module queue_ui is enabled or can be take over by Hydroponics Service and end ingested eventually

Since I left a checkbox there for "Enqueue but do not process Batch" I'm ~not~ *now* working on the opposite action, the actual process immediately (means you uncheck and you press Process), but I have a few questions here:

 I can trigger a direct Batch process. That is simple enough and testing that now *hurra for me*. Now these are the questions/facts

1. Since all future ADOs are right now going to the Same queue I would need to do something funny (which I do not like) to only process the ones from the current set. I have to go Item by Item in the queue Claiming Items and checking if they belong to the current Set ID, if so, processing can be done, if not I need to release the Items and keep claiming. This adds some overhead (and some calculation math from my part), but also has the benefit that I can actually process only Certain Sets even if the Repo is being used by multiple users and has a lot of pending Sets. Claiming Items (even if I'm going to release them) may, on concurrent processing mess thing up, because of the Ingest order we try to impose (collections and parents first, then children).
2. On "process now" action (checkbox unselected) instead of pushing to general Ingest QUEUE i can create "SET ID named" queues that are only valid for a particular set, and manually batch process them. I was thinking this may be a good idea if I can, actually delete the queue completely once the Ingest is done. Since "deleteQueue" actually deletes the table, it would not leave any garbage around, and in case of processing interruption I could even allow the user to keep processing that one at a later time... (not sure I like that... but may be needed). This discrete queue would also allow a full separation. But the ones in that queue (for immediate processing) would never ever go to the main global once, except if processing is run again but without the "checkbox" enabled.  This last option (you run once with immediate, then another one with not) may mean that the same ADOs may end enqueue twice. AMI is smart enough to not "double" ingest but pretty sure it can not be smart enough to now "double" update of "double patch"!  So next question..
3. Should, independently of the choice, only one enqueueing be possible per set? and only once all ADOs are processed and claimed and removed, a new enqueuing is possible? This sounds like a great idea, but it is tricky. Because how do I know that, e.g, all items in the Global Queue for a given set, are already processed without doing exactly what I might want avoid in 1.?
Easy enough if temp/discrete queue per set is used, but not on the global one.
4. The undo queue, for patch and update. Everyone likes undo's. This may be a killer feature, but again, tricky to implement. Should I enable a discrete/temp queue for undoing patching and updating? Or should we relay on the NODE revisions to simply keep track of those and revert to the "pre" update revision if so? If so, an undo queue, can only exist on per Set at the time and only if we are processing. But there are so many ways we can end with a strange undo queue. Like partially undo? but not all Undo if processing was interrupted?

Side note: in any case i would like to preserve the global ingest one since it allows like "all the enqueue things" to be ingested when the server is idle and in a sequential order FIFO. Still, I'm starting to feel that temp/create and delete Temp queues for immediate ingesting are a good thing...

Does any of these make sense? Should i remove the too many options and try to avoid confusing the user?And if so, what do you think is the best way? I mean, users should not be exposed to these details at all? Thanks

**Comment by DiegoPino** [comment]
In the same tone of this:

I might want to acquire a Drupal Lock when immediate Processing is requested.

 $lock = Drupal::lock();
 if ($lock->acquire('ami_set_process_1', 10.0)) { // 10 seconds per ADO, this sounds good since a single one is not taking more than 2 seconds, but this may vary?
        // Batch process, keep renewing the Lock while its running   
}

**Comment by giancarlobi** [comment]
@DiegoPino I think it's a good idea a dedicated queue for ingest AMI specific set ID. In archipelago philosophy we have to manage that as simple as possible, without confusing user so:
- an AMI item can be added only to one queue, specific or hydroponics and with only one flag for the user to be clear
- hydroponics and immediate queue are to be completely independent regarding execution and code and everything
- immediate queues are to be one at time because if you want parallel processing then use hydroponics
- I think undo queue is a complexity that we don't need and use node revision could be enough. As extreme idea could be an ADO export (does AMI allow this?) of current ADO before ingesting, but not sure this make sense.

**Comment by DiegoPino** [comment]
@giancarlobi as always thanks for your feedback. Yes, consistency is the key. Yes, the flag is one only in the new pull. I feel my wording there is confusing (the fact that checkbox checked means "enqueue" instead of "process immediately"? But still its a single one
Yes. Also, immediate queue are not parallel (at least in the sense of Per Set, per User, since really multiple users could process multiple batches via the UI, not sure I can control that other than establishing Drupal Locks).

The undo queue may only make sense if Reverting a revision is not automatized. I feel that is something I can do, but only for Update/Patch operations. 

AMI export: That would be nice. I guess I could do that using a very simple approach on a spreadsheet where each column is a JSON key and the values actually JSON snippets? I will think about that

**Comment by giancarlobi** [comment]
> AMI export: That would be nice. I guess I could do that using a very simple approach on a spreadsheet where each column is a JSON key and the values actually JSON snippets? I will think about that

@DiegoPino I was thinking in AMI export based on my current workflow in I7 to manage DC:
- a script extract DC from a collection and create a CSV file with DC elements as title of the columns
- librarians edit CSV file adding/editing DC entries (a row for each volume)
- librarians return CSV and a second script generate single DC.xml
- each DC xml are ingested by drush update command

Just in case for some more ideas.

**Comment by DiegoPino** [comment]
Yes! We want the "roundtrip" experience. Factor I may need to solve is the hierarchical JSON in a cell.
Once way of dealing with that is allowing a single object to span to multiple Rows. That requires, to make things for the ingester easier, also a ROW_NUM column, since the parent/child relationship would be easier to manage in that case by not using the actual ROW number (which will be shifted every time you add a new value under a Column). 

Sadly this [function here I wrote](https://github.com/esmero/ami/blob/main/src/AmiUtilityService.php#L882-L1083) is rocket science and I always fear I will break everything if I change it. That one is that builds the hierarchy, checks if UUIDs are valid and parents present and orders the ingest queue from parents first to children later. If not using (or allowing as alternative) a ROW ID column the change will just need to happen there.

**Comment by DiegoPino** [comment]
Resolved for now via https://github.com/esmero/ami/commit/ee93a1516e5d95d8fd092d4b33070743bbe0ad44
I will use the feedback here for other ISSUEs and the next steps. Thanks people
