### ISSUE TITLE
Update Actions and Revisions + Moderation States

### ISSUE THREAD

**Issue by alliomeria** [esmero/ami#90]
# What?

For AMI sets that use the 'Update existing ADOs' Operation, a new Revision is not created if the existing ADOs are Unpublished. 

Relatedly, if users also select the option to change the Moderation State of an Update AMI Set, from Unpublished to Published, the Moderation State will not change (objects will stay as Unpublished).

# What's needed?

The Update Operation should create a new Revisions for effected ADOs, with both Published and Unpublished status. The Update Operation should also follow the specified "Desired ADOs statuses after this update operation process."

Thank you @DiegoPino for identifying what's happening with this and working on a solution. 🐝

**Comment by DiegoPino** [comment]
Solved via https://github.com/esmero/ami/commit/4025e4e5e6bcf35107797f8a80c93e396fed710a
