### ISSUE TITLE
Invoke hook_format_strawberryfield_twigcontext_alter during AMI metadatadisplay preview 

### ISSUE THREAD

**Issue by patdunlavey** [esmero/ami#96]
I think this was an oversight. I propose that [here](https://github.com/esmero/ami/blob/0.4.0/src/Controller/AmiRowAutocompleteHandler.php#L243) we add...

```
          // Allow other modules to provide extra Context!
          // Call modules that implement the hook, and let them add items.
          \Drupal::moduleHandler()
            ->alter('format_strawberryfield_twigcontext', $context);
```
Does this sound ok with you, @DiegoPino ?

**Comment by patdunlavey** [comment]
PR created: https://github.com/esmero/ami/pull/97

**Comment by DiegoPino** [comment]
Solved via https://github.com/esmero/ami/commit/f8b562eebed14ea24dcd6753e26db54b8898d4a6 Thanks @patdunlavey !
